### ISSUE TITLE
a wild suggestion has appeared!

### ISSUE THREAD

**Issue by Quezler** [MostafaSabry55/Mana-Liquidizer#1]
hi, first of all: wonderful mod, long range mana transport is a pain and this mod fills that niche nicely 👍 

secondly, could you add the github link to the mod page on curse? (i found this repo through another mod that did have it) 😗 

![Screen Shot 2020-11-18 at 09 38 57](https://user-images.githubusercontent.com/3179271/99506219-1df4c580-2982-11eb-8a40-644dc9072108.png)

> also, have a github star! ⭐

**Comment by SpaceXVI** [comment]
Thank you, and yes I will but I'm sorry :
> (i found this repo through another mod that did have it)

What? Explain this, please

**Comment by SpaceXVI** [comment]
Oh I think I misunderstood, I'm an idiot :facepalm: , but thank you for reminding me again!

**Comment by Quezler** [comment]
closing this since its resolved 🔗
