### ISSUE TITLE
[1.16.4] Liquidizer block is always reset to "fluid to mana" on loading a world

### ISSUE THREAD

**Issue by Shandoo94** [MostafaSabry55/Mana-Liquidizer#2]
Mana Liquidizer 1.5
Botania 1.16.3-409
Forge 35.1.7

When loading a world the mana liquidizer block is reset to "liquid to mana" although on closing the world it was set to "mana to liquid"

**Comment by SpaceXVI** [comment]
Huh, I thought I saved the value to the tile's NBT? I will check now, thank you for notifying me

**Comment by SpaceXVI** [comment]
Ah, it actually resets, I will see what's the problem

**Comment by SpaceXVI** [comment]
Alright, fixed the problem and pushed an update, should hopefully be approved asap by curseforge.

Thanks for reporting this bug!
