### ISSUE TITLE
Allow users to change the input fluid for the mana liquidizer

### ISSUE THREAD

**Issue by SpaceXVI** [MostafaSabry55/Mana-Liquidizer#4]
Check the 8th and 9th comment in [https://github.com/MostafaSabry55/Mana-Liquidizer/pull/3](url) for more info.

But basically this is so that if people dislike my mana fluid, they can use something like wizardy mana or even their own contenttweaker fluid, just any fluid the users put in the config.

Now this comes with a downside tho, it will be the ONLY fluid you can get out of the transition and back in for botania's mana.

**Comment by SpaceXVI** [comment]
Very easy, successfully integrated that system, one thing is that people will have to refresh their mana liquidizer (switch between "to mana" and "to mana fluid") but yeah, it works!!

**Comment by HipHopHuman** [comment]
Well that was fast 😅 I was just in the middle of typing a suggestion that would address the downside, but it made more sense in my head than it did when actually written down :P

**Comment by SpaceXVI** [comment]
Eh I mean the downsides are minor, not that much of a problem! Anyways thank you for this suggestion
