### ISSUE TITLE
Suggestion: Input-Only Mode

### ISSUE THREAD

**Issue by HipHopHuman** [MostafaSabry55/Mana-Liquidizer#5]
Hello again! I have been using your mod alongside Create in a custom private Garden of Glass modpack I'm playing with a friend, and we have gotten to the point where we are basically using Create's pipes to transport liquid mana on an industrial scale. It has been really fun, but I've started to notice that transporting mana has become extremely easy and it kind of "breaks" Botania. 

I know that you're probably aware of this already, and I personally don't mind it, but I was thinking that since you added support for custom fluids, another modpack maker may want to use your mod to bridge Botania with another mod but without breaking Botania's transport system.

What do you think about adding a config setting that limits the mana liquidizer to an "input-only" mode, where it can convert mana to liquid, but not the other way around?

**Comment by SpaceXVI** [comment]
Great idea, I personally think the one way route for the exchange config sounds really good, will implement this soon.

**Comment by SpaceXVI** [comment]
Would it also be better if I made another config to allow an output (to botania mana) only mode? I am thinking that can be useful at some point.

**Comment by SpaceXVI** [comment]
Added in update 2.1.0, should be available on curseforge soon

**Comment by HipHopHuman** [comment]
Dang that was quick 😅

> Would it also be better if I made another config to allow an output (to botania mana) only mode? I am thinking that can be useful at some point.

I did think about this, but didn't suggest it because I mostly had Botania's balance in mind at the time of making this issue. Generally, the more flexible a mod's config, the more a packmaker will be likely to use it, so it doesn't hurt to have it work that way too :)

**Comment by HipHopHuman** [comment]
I just remembered seeing talk of an "RF Liquidizer"  mod on your CF comments page. Thanks to this feature, and the custom fluid type feature, if an RF to fluid mod existed, then these changes could be used to convert RF to Mana 😂 

RF -> RF Fluid -> Mana Liquidizer -> Mana -> Profit

Just thought it was funny.

**Comment by SpaceXVI** [comment]
Honestly I am planning to make an RF to Mana block soon :)
